version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ../create.sql:/create.sql
    ports:
      - 5432:5432